parts:
  mon-app:
    plugin: python
    source: .
    python-packages: [flet]
    stage-packages:
      - libmpv2 
      - libgl1
apps:
  mon-app:
    command: bin/python3 $SNAP/main.py
    extensions: [gnome] 
