name: lmrtask
base: core22
version: '1.0'
summary: To-Do List moderne en Python
description: |
  Application To-Do List moderne développée avec Flet.

grade: stable
confinement: strict
architectures:
  - build-on: amd64
  - build-on: arm64

apps:
  lmrtask:
    command: python3 $SNAP/main.py
    extensions: [gnome]
    desktop: snap/gui/lmrtask.desktop
    plugs:
      - network
      - desktop
      - desktop-legacy
      - wayland
      - x11
      - opengl

parts:
  app:
    plugin: python
    source: ..
    python-packages:
      - flet
    stage-packages:
      - python3-tk
    stage:
      - -usr/lib/python*/dist-packages/**/tests
      - -usr/lib/python*/dist-packages/**/test
      - -usr/lib/python*/dist-packages/**/*.pyc
      - -usr/lib/python*/dist-packages/**/*.pyo
      - -usr/lib/python*/dist-packages/**/__pycache__
      - -usr/share/doc
      - -usr/share/man
      - -usr/share/locale