name: lmrtask
base: core22
version: '1.0'
icon: icon.png
summary: To-Do List moderne en Python
description: |
  Application To-Do List moderne développée avec Flet.

grade: stable
confinement: strict

apps:
  lmrtask:
    command: bin/python3 -m main
    plugs:
      - network
      - desktop
      - desktop-legacy
      - wayland
      - x11
      - opengl

parts:
  lmrtask:
    plugin: python
    source: .
    python-packages:
      - flet

      - customtkinter==5.2.2
      - darkdetect==0.8.0
      - flet==0.28.3
      - flet-desktop==0.28.3
      - greenlet==3.3.0
      - idna==3.11
      - lxml==6.0.2
      - Mako==1.3.10
      - MarkupSafe==3.0.3
      - oauthlib==3.3.1
      - packaging==25.0
      - pillow==12.0.0
      - PyQt6==6.10.1
      - PyQt6-Qt6==6.10.1
      - PyQt6-WebEngine==6.10.0
      - PyQt6-WebEngine-Qt6==6.10.1
      - PyQt6_sip==13.10.3
      - python-docx==1.2.0
      - pywebview==6.1
      - QtPy==2.4.3
      - repath==0.9.0
      - six==1.17.0
      - SQLAlchemy==2.0.45
      - typing_extensions==4.15.0


